convertMinioError: stop shadowing minio error with os.ErrNotExist (#31)
* convertMinioError: stop shadowing minio error with os.ErrNotFound

`convertMinioError` would ignore the actual error and return `os.ErrNotFound` when the StatusCode field of minio error is 404.
Now, `os.ErrNotFound` and the minio error are wrapped together, allowing to propagate the original meaning of the error.

* convertMinioError: wrap only one err, differentiate call from doList

* convertMinioError: keep more readable `err` variable instead of `e`